version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01

    working_directory: /home/ubuntu
    steps:
    # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Print Out current status
          command: |
            users
            pwd
            ls -all

      - run:
          name: Clone plasma-evm-networks
          command: |
            git clone -b extention/docker https://github.com/Onther-Tech/plasma-evm-networks

      - run:
          name: Start container and verify it's working
          command: |
            cd plasma-evm-networks/private-testnet
            docker-compose up 
